#include <unitcode/msrvcomm.h>
int main(int argc, char *argv[])
{
    MSrvCommUnit* srvcommunit = new MSrvCommUnit();
    MLoopGroupMt<tagSrvCommLinkMsg>* loopgroupmt = new MLoopGroupMt<tagSrvCommLinkMsg>();
    tagSrvCommLinkMsg srvcommlinkmsg;
    loopgroupmt->GetData(&srvcommlinkmsg);

    tagSrvCommLinkMsgQueue LinkMsg = {
        {
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg,
            srvcommlinkmsg},
        4};
    tagSrvCommDataMsgQueue DataMsg = {
        {
             0,  1,  2,  3,
             4,  5,  6,  7,
             8,  9, 10, 11,
            12, 13, 14, 15,
            16, 17, 18, 19,
            20, 21, 22, 23,
            24, 25, 26, 27,
            28, 29, 30, 31,
            32, 33, 34, 35,
            36, 37, 38, 39,
            40, 41, 42, 43,
            44, 45, 46, 47,
            48, 49, 50, 51,
            52, 53, 54, 55,
            56, 57, 58, 59,
            60, 61, 62, 63},
        4};
    srvcommunit->Select(1, &LinkMsg, &DataMsg); //target call
    return 0;
}
